### ISSUE TITLE
[Suggestion] Back up current files & select a slot

### ISSUE THREAD

**Issue by E-RELevant** [Zamiell/isaac-save-installer#1]
Appreciate the great work!
Unfortunately, I'm yet to completely understand the GO language, so here are some suggestions:

1. Add an option to back up the current (latest) `*.dat` files to a path on the machine.
    - Explanation: Before agreeing to delete the current saved files, ask the user whether they would like to back up their current files. If so, ask them to mention a path (in my opinion, the default should be a sub-directory under `C:\Users\<USER>\Documents\My Games\Binding of Isaac Repentance\_Backup`).
    - The files themselves, should be similar to the current format of `<DATE>_<TIME>.<VERSION>_persistentgamedata<SLOT>.dat`

2. Let the user decide in which slot they want to install a save file for.
    - Explanation: Give the user the option to choose between the entire 3 slots or to mention a specific slot(s) to replace with. It could be something simple like entering the numbers 1-3 separated by commas, or spaces, or not separated at all (Make sure to filter out any other number).

**Comment by Zamiell** [comment]
> Add an option to back up the current (latest) *.dat files to a path on the machine.

no, this is out of scope for the program.
backing up the save files requires access to the windows registry, which (i think) requires the program to be run as administrator.
the user is expected to manage their own save files, i won't be held liable for a bug in the program causing someone to lose their save file.

> Let the user decide in which slot they want to install a save file for.

no, this is confusing because if an end-user only installs to e.g. slot 2, then slot 1 and 3 will appear empty and end-users will think this is a bug in the program because they don't understand how steamcloud works

**Comment by Zamiell** [comment]
this is implemented now in the latest version
